version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "monthly"
      time: "04:00"
    versioning-strategy: increase
    labels:
      - "dependencies"
    groups:
      core-dependencies:
        patterns:
          - "rocket-*"
          - "diesel-*"
      non-core-dependencies:
        exclude-patterns:
          - "rocket-*"
          - "diesel-*"
