services:

  api:
    extends: rust-release
    container_name: cron-mon-api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    command: ./api
    networks:
      - default
      - cron-mon-network

  api-debug:
    extends: rust-cargo
    container_name: cron-mon-api-debug
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    command: cargo run --bin api
    networks:
      - default
      - cron-mon-network

  monitor:
    extends: rust-release
    container_name: cron-mon-monitor
    depends_on:
      db:
        condition: service_healthy
    command: ./monitor
    networks:
      - default
      - cron-mon-network

  monitor-debug:
    extends: rust-cargo
    container_name: cron-mon-monitor-debug
    depends_on:
      db:
        condition: service_healthy
    command: cargo run --bin monitor
    networks:
      - default
      - cron-mon-network

  integration-tests-rs:
    extends: rust-cargo
    container_name: rust-integration-tests
    depends_on:
      db:
        condition: service_healthy
    command: cargo test --no-fail-fast --test "*" -- --test-threads=1
    networks:
      - default
      - cron-mon-network

  db:
    container_name: cron-mon-db
    image: public.ecr.aws/docker/library/postgres:16.1
    environment:
      POSTGRES_USER: cron-mon-api
      POSTGRES_PASSWORD: itsasecret
      POSTGRES_DB: cron-mon
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]

  seeder:
    container_name: cron-mon-db-seeder
    build:
      dockerfile: ./api/src/infrastructure/seeding/Dockerfile
      context: .
    environment:
      PGHOST: cron-mon-db
      PGUSER: cron-mon-api
      PGPASSWORD: itsasecret
      PGDATABASE: cron-mon
    volumes:
      - ./api/src/infrastructure/seeding/seeds.sql:/usr/share/seeds.sql
    depends_on:
      db:
        condition: service_healthy
    command: psql -f /usr/share/seeds.sql

  rust-release:
    image: cron-mon/rust-release-image
    build:
      dockerfile: ./Dockerfile
      context: .
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon
      CARGO_HOME: /usr/cron-mon/.cargo
    volumes:
      - ./api:/usr/cron-mon/api

  rust-cargo:
    image: cron-mon/rust-cargo-image
    build:
      dockerfile: ./Dockerfile
      context: .
      target: builder
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon
      CARGO_HOME: /usr/cron-mon/.cargo
    volumes:
      - ./api:/usr/cron-mon/api

networks:
  cron-mon-network:
    driver: bridge
    name: cron-mon-network

volumes:
  postgres-data:
    name: cron-mon-postgres-data
