[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"]}
uuid = { version = "1.8.0", features = ["v4", "serde", "fast-rng", "macro-diagnostics"] }