[package]
name = "cron-mon-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
chrono = { version = "0.4", features = ["serde"]}
diesel = { version = "2.1.6", features = ["chrono", "uuid", "postgres"] }
diesel-async = { version = "0.4.1", features = ["postgres"] }
diesel_migrations = { version = "2.1.0", features = ["postgres"] }
figment = "0.10.19"
rocket = { version = "0.5.1", features = ["json", "uuid"] }
rocket_db_pools = { version = "0.2.0", features = ["diesel_postgres" ]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.17"
tokio = { version = "1.38.0", features = ["test-util"] }
uuid = { version = "1.9.1", features = ["v4", "serde", "fast-rng", "macro-diagnostics"] }

[dev-dependencies]
rstest = "0.21.0"
pretty_assertions = "1.4.0"
test-utils = { path = "test_utils" }

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "monitor"
path = "src/bin/monitor.rs"
