[default]
address = "0.0.0.0"
ident = "Cron Mon API"

[debug]
ident = "Cron Mon API - debug"

[github]
ident = "Cron Mon API - GitHub Actions"

[default.databases.monitors]
url = "postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon"

[vscode.databases.monitors]
url = "postgres://cron-mon-api:itsasecret@host.docker.internal:54320/cron-mon"
<<<<<<< HEAD
=======

[github.database.monitors]
url = "postgres://cron-mon-api:itsasecret@postgres/cron-mon"
>>>>>>> parent of bbf4139 (Revert "chore: Try running integration tests in a container in CI (again)")
