[default]
address = "0.0.0.0"
ident = "Cron Mon API"
log_level = "normal"

[debug]
ident = "Cron Mon API - debug"

[release]
ident = "Cron Mon API (prod)"

[github]
ident = "Cron Mon API - GitHub Actions"

[default.databases.monitors]
url = "postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon"

[release.databases.monitors]
url = "postgres://cron-mon-api:itsasecret@host.docker.internal:54320/cron-mon"

[vscode.databases.monitors]
url = "postgres://cron-mon-api:itsasecret@host.docker.internal:54320/cron-mon"
