on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.77.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo check
        run: cd api && cargo check

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.77.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo test
        run: cd api && cargo test --bins

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:16.1
        env:
          POSTGRES_USER: cron-mon-api
          POSTGRES_PASSWORD: itsasecret
          POSTGRES_DB: cron-mon
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.77.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo test
        run: cd api && cargo test --test integration_test
        env:
          DATABASE_URL: postgres://cron-mon-api:itsasecret@localhost/cron-mon
