on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.77.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo check
        run: cd api && cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.77.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo test
        run: cd api && cargo test
