name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.80.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo fmt and clippy
        run: make lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install rust
        run: rustup install 1.80.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run cargo test
        run: make unit-test

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    container: public.ecr.aws/docker/library/rust:1.80.0-slim
    services:
      cron-mon-db:
        image: public.ecr.aws/docker/library/postgres:16.1
        env:
          POSTGRES_USER: cron-mon-api
          POSTGRES_PASSWORD: itsasecret
          POSTGRES_DB: cron-mon
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install build-essential libpq-dev libssl-dev pkg-config -y
          cargo install diesel_cli --no-default-features --features postgres

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run migrations
        run: make migrate
        env:
          DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon

      - name: Run integration test
        run: make integration-tests
        env:
          DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon

  test-coverage:
    name: Test coverage
    needs: [lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    container: public.ecr.aws/docker/library/rust:1.80.0-slim
    services:
      cron-mon-db:
        image: public.ecr.aws/docker/library/postgres:16.1
        env:
          POSTGRES_USER: cron-mon-api
          POSTGRES_PASSWORD: itsasecret
          POSTGRES_DB: cron-mon
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install build-essential libpq-dev libssl-dev pkg-config -y
          rustup component add llvm-tools-preview
          cargo install grcov
          cargo install diesel_cli --no-default-features --features postgres

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "api"

      - name: Run migrations
        run: make migrate
        env:
          DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon

      - name: Run cargo test
        run: make test-coverage
        env:
          DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon

  build-and-push-image:
    name: Build and push container image to ghcr.io
    needs: test-coverage
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=long,prefix=

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
